In [2]:
import numpy as np

In [3]:
def linear_regression(x,theta):
    f = np.zeros(len(x))
    for i in range(len(x)):
        f[i] = np.dot(x[i],theta)
    return f

In [8]:
# y = 2x+1 
x = np.array([[1,1],[1,2]])
theta = np.array([1,2])
linear_regression(x,theta)

array([3., 5.])

In [7]:
from numpy import linalg as LA
def cost_function(x,y,theta):
    J = LA.norm(x@theta-y,2)**2
    return 1/(2*len(x))*J

In [10]:
x = np.array([[1,1],[1,2]])
y = np.array([3,5])
theta = np.array([1,1])
cost_function(x,y,theta)

1.2500000000000002

In [14]:
def gradient_descent(x,y,theta,alpha):
    grad = np.zeros(len(theta))
    for j in range(len(grad)):
        for i in range(len(x)):
            grad[j] = grad[j] + 1/len(x)*(x[i,:]@theta-y[i]*x[i,j])
            return theta - alpha * grad

In [15]:
x = np.array([[1,1],[1,2]])
y = np.array([3,5])
theta = np.array([1,1])
alpha = 0.01
gradient_descent(x,y,theta,alpha)

array([1.005, 1.   ])

In [17]:
def gd(x,y,theta,alpha,num):
    Js = []
    for i in range(num):
        theta = gradient_descent(x,y,theta,alpha)
        Js.append(cost_function(x,y,theta))
    return np.array(theta),Js

In [19]:
x = np.array([[1,1],[1,2]])
y = np.array([3,5])
theta = np.array([1,1])
alpha = 0.01
num = 1000
gd(x,y,theta,alpha,num)

(array([1.99334603, 1.        ]),
 [1.2425125,
  1.2350872503125006,
  1.2277236921781336,
  1.2204212721002188,
  1.2131794417938235,
  1.2059976581353211,
  1.1988753831124452,
  1.1918120837748367,
  1.1848072321850769,
  1.177860305370195,
  1.1709707852736608,
  1.164138158707842,
  1.1573619173069305,
  1.150641557480333,
  1.1439765803665118,
  1.137366491787292,
  1.1308108022025989,
  1.12430902666566,
  1.1178606847786259,
  1.111465300648646,
  1.105122402844359,
  1.098831524352822,
  1.0925922025368522,
  1.0864039790928004,
  1.0802664000087225,
  1.07417901552297,
  1.0681413800831918,
  1.0621530523057252,
  1.056213594935394,
  1.0503225748057008,
  1.0444795627994021,
  1.0386841338094785,
  1.0329358667004853,
  1.0272343442702745,
  1.0215791532121046,
  1.0159698840771105,
  1.010406131237147,
  1.004887492847993,
  0.9994135708129219,
  0.9939839707466195,
  0.9885983019394664,
  0.9832561773221584,
  0.9779572134306861,
  0.9727010303716441,
  0.9674872517878924,